### PR TITLE
feat!: move to ESM, generated typescript types from JSDoc

### LINKED ISSUE #43: Upgrade to check-links@^2.0.0?
Hi @davidtheclark @ChristianMurphy @transitive-bullshit, thanks for this remark-lint plugin, very useful!

Would you be open to upgrading to `check-links@^2.0.0`?

It addresses a security vulnerability in the transitive dependency `got`: 

- PR: https://github.com/transitive-bullshit/check-links/pull/20#issuecomment-1307872966
- Advisory: https://github.com/advisories/GHSA-pfrx-2q88-qq97

### PR DESCRIPTION
**Pull request by ChristianMurphy**
This is a major version update, this makes several significant changes:
* Move to ESM
* Generate TypeScript typings from JSDoc comments
* Update dependencies to latest version
* Align with development tools commonly used by `remarkjs` projects

~Still TODO~ Completed:
- [x] Migrate test suite to an ESM compatible tool (~likely `tape`~, `node:test` and `node:assert`)
- [x] Resolve missing typings, may require an upstream change at `check-links`
- [x] Update documentation
- [x] Move CI to GitHub actions
- [x] 100% test coverage

Resolves #43 #28 #30 #33 #34 #36 #37 #40 #42

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
opened https://github.com/transitive-bullshit/check-links/pull/23 to add missing typings

**Comment by ChristianMurphy** [comment]
Friendly ping @davidtheclark 🔔 
This is ready for review.

An example of the build status/results https://github.com/ChristianMurphy/remark-lint-no-dead-urls/actions/runs/3483150219

**Comment by karlhorky** [comment]
Just checking in on this again, @davidtheclark what do you think about this PR?

**Comment by davidtheclark** [comment]
I am not really maintaining this anymore. I'd be happy to hand it off to anybody who would like to take over!

**Comment by karlhorky** [comment]
Oh, @ChristianMurphy or @transitive-bullshit, would you be able to do some maintenance work on this? I think both of you would be better candidates than me.

**Comment by ChristianMurphy** [comment]
Heya @davidtheclark!
I think there'd be some interest in `remarkjs` (https://github.com/remarkjs) to keep this project maintained.
We have a bit more on how projects are managed and transfer can happen in: https://github.com/unifiedjs/collective/blob/55dd48e1747af1372d0fd8ef92662b4064f5d47a/organizations.md#management

To summarize the steps:
1. Check if there is interest in handing off? Yes ✅ (https://github.com/davidtheclark/remark-lint-no-dead-urls/pull/44#issuecomment-1427177735)
2. Move the GitHub repo `remarkjs`
   * We could fork the repo (which would mean a reset of issues and PRs)
   * You could transfer the repo (directly to `remarkjs` if GitHub allows it, or to @wooorm or @ChristianMurphy, and we could move it in)
3. Make sure you (@davidtheclark) still have collaborator access to the GitHub repo (Transfers can mess with permissions 😞)
4. Add @wooorm as an owner on the npm package
5. Done

**Comment by wooorm** [comment]
For step 2 above, I don’t think forking is a good idea. I’d rather you move the repo to one of us, then we can move to the org.

For step 3, I’d ask: are you still interested in occasionally contributing to the repo?
If not, you will not have extra access to the repo later. You can still contribute like normal to OSS of course, though.
If yes, you can be added but will have less permissions than you currently do. You will also have to confirm that you have 2FA enabled on GitHub, and that you have read and agree to abide with our [code of conduct](https://github.com/unifiedjs/collective/blob/55dd48e1747af1372d0fd8ef92662b4064f5d47a/code-of-conduct.md)?

**Comment by davidtheclark** [comment]
@ChristianMurphy @wooorm: I've initiated an ownership transfer to @wooorm -- I was unable to transfer directly to the `remarkjs` organization. I do not need special access to the new repository: I'd be happy to contribute in regular OSS ways in the future if I do. Let me know if you need anything else!

**Comment by wooorm** [comment]
Moved! Thanks :)

**Comment by wooorm** [comment]
Can you add me on npm too? https://www.npmjs.com/package/remark-lint-no-dead-urls

**Comment by wooorm** [comment]
@ChristianMurphy I believe you now have access to merge some of your work. Feel free to ask my reviews / merge stuff yourself / work on this repo for a bit. I can look into some of the docs/urls stuff in some of the coming days!

**Comment by ChristianMurphy** [comment]
Thanks @davidtheclark and @wooorm!

> Feel free to ask my reviews / merge stuff yourself / work on this repo for a bit.

I'm going to land this PR now, and will probably open some smaller PR over the coming days.

> I can look into some of the docs/urls stuff in some of the coming days!

Sounds good, thanks!

**Pull request merged**
