### PR TITLE
Added a customizeErrorMessage function to the options

### PR DESCRIPTION
**Pull request by LokeshNSF**
- Added a customizeErrorMessage function to provide an ability to customize the dead url error message
- Updated readme doc.
- Updated tests

### CODE REVIEW

**Comment by LokeshNSF** [comment]
@davidtheclark We have a requirement in our team to customize the dead url error message. I have implemented the same here. Please have a look and let me know if this is ok. Thanks!

**Comment by LokeshNSF** [comment]
Hi @zivl @davidtheclark @ChristianMurphy , Can you please take a look at this PR and let me know if this is ok. Thanks!

**Comment by ChristianMurphy** [comment]
I'm not sure it makes sense to have this at an individual lint rule level.
Take for example, if someone wanted custom message for each of the 70 some rules in https://github.com/remarkjs/remark-lint
Would all 70 packages/rules need to re-implement this same function/option? That feels off :thinking: 

Maybe this could live in https://github.com/remarkjs/remark-lint/tree/main/packages/unified-lint-rule or https://github.com/remarkjs/remark-message-control ? :thinking: 

/cc @wooorm

**Comment by wooorm** [comment]
Maybe. It’s always good to look at how other linters do it. Solving this nicely would probably come with complex schema, e.g.,:

https://github.com/mysticatea/eslint-plugin-node/blob/cd97880ca2792db47c7952ac517e9e32d2ec783e/lib/rules/no-sync.js#L8-L33

However, I don’t think ESLint supports changing messages. I also don‘t really see a strong need (because there is a good alternative: use a plugin after it that changes message). And I’m not sure what the API would be to change them. A function seem off to me

**Comment by ChristianMurphy** [comment]
Thanks @LokeshNSF!
I think adding another plugin after makes sense, if you have questions on how that would work, feel free to follow up in a discussion https://github.com/orgs/remarkjs/discussions

**Pull request closed without merging**
